### ISSUE TITLE
Pin 37 mislabeled

### ISSUE THREAD

**Issue by makasaurus** [davecheney/mega6502#1]
Pin 37 is labeled as PHI0 but it seems that it should be labeled as PHI2.

See http://www.jameco.com/Jameco/Products/ProdDS/2143638.pdf

**Comment by davecheney** [comment]
Nope, not on the R65C02 phi0 (in) is pin 37, phi2 (out) is pin 39. The WDC 65C02's dispensed with the PHI0 entirely, calling it PHI2 and and PHI2 OUT, just to make things even more confusing.
